const express = require('express');
const router = express.Router();
const auth = require('../auth/auth');
const controller = require('../controller/controller');
router.post('/signup', controller.signup);
router.post('/login', controller.login);
router.get('/todos', auth, controller.getTodos);
router.post('/add', auth, controller.addtodo);
router.delete('/delete/:id', auth, controller.deletetodo);
module.exports = router;